// Generated by CoffeeScript 1.6.3
(function() {
  var Person;

  Person = (function() {
    function Person(name) {
      this.name = name != null ? name : "Stranger";
    }

    return Person;

  })();

  document.addEventListener("DOMContentLoaded", function() {
    var peep;
    peep = new Person();
    return document.getElementById("output").textContent = "Hello " + peep.name + "!";
  });

}).call(this);

/*
//@ sourceMappingURL=helloworld.map
*/
